import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";

import { Roboto } from 'next/font/google';
import "./globals.css";
import Header from "./components/Header";
import Nav from "./components/Nav";
import Footer from "./components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'], // adjust as needed
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        
        <Header />
        <Nav />
        {children}
        <Footer />
      

      </body>
    </html>
  );
}
